### ISSUE TITLE
Instagram Login is not working for me

### ISSUE THREAD

**Issue by bruno-martins** [abynim/SketchSquares#10]
I'm on a never ending cycle of login attempts to Instagram.
I haven't been able to use the plugin yet. 
I'm using Yosemite 10.10.3 and Sketch 3.3.2 and my Instagram credentials are correct.

This is what it shows to me:

![screen shot 2015-06-10 at 14 39 29](https://cloud.githubusercontent.com/assets/3820469/8083737/b20673f0-0f7e-11e5-8abf-f7073afcf055.png)

**Comment by abynim** [comment]
@bruno-martins From the screenshot it looks like you were signed in (since you can see the 'Load Photos' dialog) but it seems your token may have expired and now you're stuck in limbo :( One thing to try is to launch Instagram in your browser and Logout from there. Then launch the plugin again and see if it forces you to log in (and get a new token in the process). Please let me know if that works. Thanks!

**Comment by bruno-martins** [comment]
It's working now, but it's a bit flaky. Takes a lot of time to load photos or doesn't load any in some cases :| not sure if it's only me having this issue.

**Comment by abynim** [comment]
The time taken to load photos is mostly based on your internet connection and the number of photos you're trying to load. The plugin waits for all photos to be downloaded before returning them back to Sketch though, which is something I'm looking to fix – by making it more responsive so it returns photos as they are loaded. Thanks for your feedback @bruno-martins. I will ping you once I have some of these optimizations in place so you can update the plugin then :)
